import { MapLocation } from "@/types";

export const GLOBAL_STARTUP_HUBS: MapLocation[] = [
  {
    city: "San Francisco / Silicon Valley",
    country: "United States",
    region: "North America",
    lat: 37.7749,
    lng: -122.4194,
    ecosystemScore: 98,
    talentIndex: "9.8/10 World-Class",
    vcFundingClimate: "Hyperactive ($32.4B Early-Stage)",
    regulatoryFriendliness: "Moderate (High litigation awareness)",
    avgCustomerAcquisitionCost: "$280 - $450",
    keyHubs: ["SoMa AI Hub", "Palo Alto Sand Hill", "Mission District", "South Park"],
  },
  {
    city: "New York City",
    country: "United States",
    region: "North America",
    lat: 40.7128,
    lng: -74.006,
    ecosystemScore: 95,
    talentIndex: "9.5/10 Premier",
    vcFundingClimate: "Strong ($18.6B FinTech & Enterprise)",
    regulatoryFriendliness: "Strict (BitLicense & NYDFS standards)",
    avgCustomerAcquisitionCost: "$240 - $390",
    keyHubs: ["Silicon Alley", "Flatiron District", "DUMBO Brooklyn", "Hudson Yards"],
  },
  {
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    lat: 51.5074,
    lng: -0.1278,
    ecosystemScore: 93,
    talentIndex: "9.3/10 Top European",
    vcFundingClimate: "Vibrant ($12.1B Fintech & Health)",
    regulatoryFriendliness: "Favorable (FCA Regulatory Sandbox pioneer)",
    avgCustomerAcquisitionCost: "$190 - $310",
    keyHubs: ["Silicon Roundabout Shoreditch", "King's Cross AI Corridor", "Canary Wharf"],
  },
  {
    city: "Bengaluru (Bangalore)",
    country: "India",
    region: "Asia-Pacific",
    lat: 12.9716,
    lng: 77.5946,
    ecosystemScore: 90,
    talentIndex: "9.6/10 Engineering Powerhouse",
    vcFundingClimate: "Rapid Growth ($8.4B SaaS & B2B)",
    regulatoryFriendliness: "Fast-Paced (Digital India & DPDP compliance)",
    avgCustomerAcquisitionCost: "₹4,500 - ₹9,000",
    keyHubs: ["Koramangala Startup Hub", "Indiranagar", "HSR Layout", "Electronic City"],
  },
  {
    city: "Mumbai",
    country: "India",
    region: "Asia-Pacific",
    lat: 19.076,
    lng: 72.8777,
    ecosystemScore: 88,
    talentIndex: "9.2/10 Financial Capital",
    vcFundingClimate: "High Density ($6.8B FinTech & Commerce)",
    regulatoryFriendliness: "Strong (RBI Innovation Hub & SEBI Sandbox)",
    avgCustomerAcquisitionCost: "₹5,000 - ₹10,500",
    keyHubs: ["BKC FinTech Hub", "Lower Parel", "Powai IIT Innovation Corridor", "Andheri"],
  },
  {
    city: "Delhi NCR (Gurugram / Noida)",
    country: "India",
    region: "Asia-Pacific",
    lat: 28.6139,
    lng: 77.209,
    ecosystemScore: 87,
    talentIndex: "9.1/10 Commerce & Enterprise",
    vcFundingClimate: "Prolific ($7.1B Consumer Tech & B2B)",
    regulatoryFriendliness: "Favorable (National Startup India policy)",
    avgCustomerAcquisitionCost: "₹4,200 - ₹8,800",
    keyHubs: ["Cyber City Gurugram", "Sector 62 Noida", "Okhla Innovation Hub"],
  },
  {
    city: "Singapore",
    country: "Singapore",
    region: "Asia-Pacific",
    lat: 1.3521,
    lng: 103.8198,
    ecosystemScore: 92,
    talentIndex: "9.1/10 Pan-Asian Leadership",
    vcFundingClimate: "Tax-Advantaged ($7.8B Southeast Asia Gateway)",
    regulatoryFriendliness: "Very High (MAS FinTech Sandbox, zero capital gains tax)",
    avgCustomerAcquisitionCost: "$160 - $270",
    keyHubs: ["Block 71 LaunchPad", "Marina Bay FinTech Center", "One-North Tech Hub"],
  },
  {
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    lat: 52.52,
    lng: 13.405,
    ecosystemScore: 89,
    talentIndex: "9.0/10 Creative & Engineering",
    vcFundingClimate: "Healthy ($6.5B CleanTech & SaaS)",
    regulatoryFriendliness: "High Privacy (Strict GDPR compliance regime)",
    avgCustomerAcquisitionCost: "$170 - $260",
    keyHubs: ["Mitte Tech Hub", "Kreuzberg Startups", "Factory Berlin"],
  },
  {
    city: "Tokyo",
    country: "Japan",
    region: "Asia-Pacific",
    lat: 35.6762,
    lng: 139.6503,
    ecosystemScore: 88,
    talentIndex: "9.2/10 Deep Hardware & Robotics",
    vcFundingClimate: "Surging ($5.9B Gov Co-Investment)",
    regulatoryFriendliness: "Structured (METI Innovation Sandboxes)",
    avgCustomerAcquisitionCost: "$210 - $340",
    keyHubs: ["Shibuya Bit Valley", "Toranomon Hills Innovation Center", "Roppongi Hub"],
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    region: "Middle East",
    lat: 32.0853,
    lng: 34.7818,
    ecosystemScore: 91,
    talentIndex: "9.7/10 Cyber & DeepTech Elite",
    vcFundingClimate: "High Density ($6.2B Cyber & AI)",
    regulatoryFriendliness: "Innovation-First (Fast patent filing & R&D grants)",
    avgCustomerAcquisitionCost: "$190 - $320",
    keyHubs: ["Rothschild Boulevard", "Herzliya Pituach", "Sarona Market Hub"],
  },
  {
    city: "Toronto",
    country: "Canada",
    region: "North America",
    lat: 43.6532,
    lng: -79.3832,
    ecosystemScore: 88,
    talentIndex: "9.3/10 Vector Institute AI Hotspot",
    vcFundingClimate: "Steady ($5.4B B2B & MedTech)",
    regulatoryFriendliness: "High (SR&ED R&D Tax Incentive program)",
    avgCustomerAcquisitionCost: "$150 - $250",
    keyHubs: ["MaRS Discovery District", "King West Silicon Strip", "Waterloo Corridor"],
  },
  {
    city: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    lat: 25.2048,
    lng: 55.2708,
    ecosystemScore: 87,
    talentIndex: "8.8/10 International Expat Magnet",
    vcFundingClimate: "Sovereign-Backed ($4.8B Future Fund)",
    regulatoryFriendliness: "Ultra-High (DIFC Innovation License, 0% personal tax)",
    avgCustomerAcquisitionCost: "$140 - $230",
    keyHubs: ["DIFC FinTech Hive", "Dubai Internet City", "Hub71 Abu Dhabi Corridor"],
  },
  {
    city: "Sydney",
    country: "Australia",
    region: "Asia-Pacific",
    lat: -33.8688,
    lng: 151.2093,
    ecosystemScore: 86,
    talentIndex: "8.9/10 High Quality",
    vcFundingClimate: "Resilient ($4.2B SaaS & GreenTech)",
    regulatoryFriendliness: "Supportive (ASIC Enhanced Regulatory Sandbox)",
    avgCustomerAcquisitionCost: "$180 - $290",
    keyHubs: ["Tech Central Sydney", "Surry Hills", "Barangaroo"],
  },
  {
    city: "São Paulo",
    country: "Brazil",
    region: "Latin America",
    lat: -23.5505,
    lng: -46.6333,
    ecosystemScore: 85,
    talentIndex: "8.7/10 Rapidly Scaling",
    vcFundingClimate: "LatAm Leader ($3.8B Fintech & Retail)",
    regulatoryFriendliness: "Moderate (PIX infrastructure advantage, LGPD laws)",
    avgCustomerAcquisitionCost: "$70 - $140",
    keyHubs: ["Faria Lima Financial Tech", "Vila Madalena", "Pinheiros Innovation District"],
  },
  {
    city: "Paris",
    country: "France",
    region: "Europe",
    lat: 48.8566,
    lng: 2.3522,
    ecosystemScore: 89,
    talentIndex: "9.4/10 Mathematics & Open-Source AI",
    vcFundingClimate: "Strong ($7.2B GenAI & DeepTech)",
    regulatoryFriendliness: "Favorable (French Tech Visa & Bpifrance non-dilutive grants)",
    avgCustomerAcquisitionCost: "$175 - $285",
    keyHubs: ["Station F", "Silicon Sentier", "Plateau de Saclay AI Cluster"],
  },
  {
    city: "Austin",
    country: "United States",
    region: "North America",
    lat: 30.2672,
    lng: -97.7431,
    ecosystemScore: 89,
    talentIndex: "9.1/10 High Influx",
    vcFundingClimate: "Booming ($6.1B Enterprise & Hardware)",
    regulatoryFriendliness: "Very High (No state income tax, pro-business climate)",
    avgCustomerAcquisitionCost: "$210 - $320",
    keyHubs: ["Silicon Hills", "Downtown Tech Corridor", "Domain Northside"],
  },
];

export const DEFAULT_LOCATION =
  GLOBAL_STARTUP_HUBS.find((h) => h.city.includes("Bengaluru")) || GLOBAL_STARTUP_HUBS[0];

export function getLocationByCity(cityName: string): MapLocation {
  const found = GLOBAL_STARTUP_HUBS.find(
    (h) => h.city.toLowerCase().includes(cityName.toLowerCase()) || cityName.toLowerCase().includes(h.city.toLowerCase())
  );
  return found || DEFAULT_LOCATION;
}
