import { StartupProject } from "@/types";

const VAULT_STORAGE_KEY = "startup_validator_cloud_vault_v1";

export function getSavedProjects(): StartupProject[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(VAULT_STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw);
  } catch (e) {
    console.error("Failed to load saved projects from vault", e);
    return [];
  }
}

export async function saveProjectToVault(project: StartupProject): Promise<void> {
  if (typeof window === "undefined") return;
  try {
    // 1. Instant local persistence
    const existing = getSavedProjects();
    const filtered = existing.filter((p) => p.id !== project.id);
    const updated = [project, ...filtered];
    localStorage.setItem(VAULT_STORAGE_KEY, JSON.stringify(updated));

    // 2. Persist to MongoDB backend asynchronously
    fetch("/api/projects", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ project }),
    }).catch((err) => {
      console.warn("MongoDB background sync note:", err?.message || err);
    });
  } catch (e) {
    console.error("Failed to save project to vault", e);
  }
}

export async function deleteProjectFromVault(id: string): Promise<void> {
  if (typeof window === "undefined") return;
  try {
    // 1. Instant local removal
    const existing = getSavedProjects();
    const updated = existing.filter((p) => p.id !== id);
    localStorage.setItem(VAULT_STORAGE_KEY, JSON.stringify(updated));

    // 2. Delete from MongoDB backend asynchronously
    fetch(`/api/projects?id=${encodeURIComponent(id)}`, {
      method: "DELETE",
    }).catch((err) => {
      console.warn("MongoDB delete sync note:", err?.message || err);
    });
  } catch (e) {
    console.error("Failed to delete project from vault", e);
  }
}

export async function syncVaultWithDatabase(): Promise<StartupProject[]> {
  if (typeof window === "undefined") return [];
  try {
    const res = await fetch("/api/projects");
    if (!res.ok) return getSavedProjects();

    const data = await res.json();
    if (data.success && Array.isArray(data.projects)) {
      const local = getSavedProjects();
      // Merge remote and local by id, preferring most recently updated
      const projectMap = new Map<string, StartupProject>();
      local.forEach((p) => projectMap.set(p.id, p));
      data.projects.forEach((p: StartupProject) => projectMap.set(p.id, p));

      const merged = Array.from(projectMap.values()).sort(
        (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
      );

      localStorage.setItem(VAULT_STORAGE_KEY, JSON.stringify(merged));
      return merged;
    }
  } catch (err) {
    console.warn("Could not sync with MongoDB database, using local cache:", err);
  }
  return getSavedProjects();
}

export function exportProjectAsMarkdown(project: StartupProject): string {
  const { selectedIdea, validation, feasibility, founderProfile } = project;
  const loc = project.targetLocation || founderProfile.targetLocation;

  return `# ${selectedIdea.name} — Institutional Startup Validation Report
*Generated by AI + API + Cloud Startup Validator on ${new Date(project.createdAt).toLocaleDateString()}*

> **Tagline:** ${selectedIdea.tagline}
> **Domain:** ${selectedIdea.domain} | **Interests:** ${founderProfile.interests?.join(", ") || "AI & Cloud SaaS"}
> **Skills:** ${founderProfile.skills.join(", ")} | **Budget:** ${founderProfile.budget}
> **Launch Ecosystem:** ${loc ? `${loc.city}, ${loc.country} (Ecosystem Score: ${loc.ecosystemScore}/100)` : "Global"}
> **Startup Viability Score:** **${feasibility.overallScore}/100 (${feasibility.verdict})**

---

## 1. Executive Summary & Problem-Solution
- **Problem Statement:** ${selectedIdea.problemStatement}
- **Solution Overview:** ${selectedIdea.solution}
- **Target Persona:** ${selectedIdea.targetPersona.title}
- **Core Pain Points:**
${selectedIdea.targetPersona.painPoints.map((p) => `  - ${p}`).join("\n")}
- **Willingness to Pay:** ${selectedIdea.targetPersona.willingnessToPay}
- **Why Now / Catalyst:** ${selectedIdea.whyNow}
- **Innovation Moat:** ${selectedIdea.innovationMoat}

---

## 2. Market Sizing & Opportunity (TAM / SAM / SOM)
- **TAM (Total Addressable Market):** ${validation.tam.value} — *${validation.tam.description}*
- **SAM (Serviceable Addressable Market):** ${validation.sam.value} — *${validation.sam.description}*
- **SOM (Serviceable Obtainable Market):** ${validation.som.value} — *${validation.som.description}*
- **Market Growth (CAGR - Compound Annual Growth Rate):** ${validation.cagr}

### Market Dynamics Overview
${validation.marketSummary}

${validation.regionalMarketDynamics ? `### Regional Geographic Ecosystem\n${validation.regionalMarketDynamics}\n` : ""}

---

## 3. Competitive Intelligence & Moat Analysis
| Competitor | Type | Strengths | Weaknesses | Our Differentiation | Funding / Scale |
|---|---|---|---|---|---|
${validation.competitors
  .map(
    (c) =>
      `| **${c.name}** | ${c.type} | ${c.strengths} | ${c.weaknesses} | **${c.ourDifferentiation}** | ${c.fundingOrScale} |`
  )
  .join("\n")}

${validation.competitorComparisonMatrix ? `
### Feature Comparison Battlecard
| Key Capability | ${selectedIdea.name} (Our Product) | ${validation.competitorComparisonMatrix.competitors.map((c) => c.name.split("(")[0].trim()).join(" | ")} |
|---|---|${validation.competitorComparisonMatrix.competitors.map(() => "---").join("|")}|
${validation.competitorComparisonMatrix.features
  .map(
    (f) =>
      `| ${f} | **Supported** | ${validation.competitorComparisonMatrix?.competitors
        .map((c) => (typeof c.scores[f] === "boolean" ? (c.scores[f] ? "Yes" : "No") : c.scores[f]))
        .join(" | ")} |`
  )
  .join("\n")}
` : ""}

---

## 4. Target User Analysis & Buying Journey
${validation.targetUserAnalysis ? `
- **Primary Persona:** ${validation.targetUserAnalysis.personaName} (${validation.targetUserAnalysis.roleTitle})
- **Organization Type:** ${validation.targetUserAnalysis.organizationType}
- **Willingness to Pay Range:** ${validation.targetUserAnalysis.willingnessToPayRange}

### Acute Pain Points
${validation.targetUserAnalysis.acutePainPoints.map((p) => `- ${p}`).join("\n")}

### Buying Trigger Moments (Purchase Catalysts)
${validation.targetUserAnalysis.buyingTriggerMoments.map((t) => `- ${t}`).join("\n")}

### Customer Acquisition Channels
${validation.targetUserAnalysis.acquisitionChannels.map((c) => `- **${c.channel}**: ${c.effectiveness} ROI (Estimated CAC: ${c.estimatedCac})`).join("\n")}

### Adoption Friction & Retention Drivers
- **Adoption Barrier:** ${validation.targetUserAnalysis.adoptionFriction}
- **Retention Drivers:**
${validation.targetUserAnalysis.retentionDrivers.map((r) => `  - ${r}`).join("\n")}
` : "Standard profile aligned with target persona."}

---

## 5. Financial & Revenue Model
- **Primary Revenue Model:** ${feasibility.revenueModel.primaryModel}
- **CAC (Customer Acquisition Cost):** ${feasibility.revenueModel.keyUnitEconomics.cacEstimate}
- **LTV (Customer Lifetime Value):** ${feasibility.revenueModel.keyUnitEconomics.ltvEstimate}
- **LTV : CAC Ratio (Lifetime Value to Acquisition Cost):** ${feasibility.revenueModel.keyUnitEconomics.ltvCacRatio}
- **Gross Margin:** ${feasibility.revenueModel.keyUnitEconomics.grossMargin}

### Pricing Tiers
${feasibility.revenueModel.pricingTiers
  .map(
    (tier) =>
      `### ${tier.tier} — ${tier.price} ${tier.billing}\n${tier.features
        .map((f) => `- ${f}`)
        .join("\n")}`
  )
  .join("\n\n")}

---

## 6. Technical Feasibility & Cloud Architecture
- **Overall Feasibility Score:** ${feasibility.overallScore} / 100
  - Technical Feasibility: ${feasibility.technicalScore}/100
  - Market Demand: ${feasibility.marketScore}/100
  - Financial Unit Economics: ${feasibility.financialScore}/100
  - Regulatory & Compliance: ${feasibility.regulatoryScore}/100
  - Speed to MVP: ${feasibility.executionScore}/100

### Cloud Infrastructure Blueprint
- **Recommended Cloud Provider:** ${feasibility.cloudArchitecture.recommendedProvider}
- **Compute Tier:** ${feasibility.cloudArchitecture.compute}
- **Database & Storage:** ${feasibility.cloudArchitecture.database}
- **AI Inference Pipeline:** ${feasibility.cloudArchitecture.aiInference}
- **Global CDN & Edge:** ${feasibility.cloudArchitecture.storageAndCDN}

### Cloud Cost Projections
- **MVP (Minimum Viable Product) Stage:** ${feasibility.cloudArchitecture.estimatedMonthlyCloudCost.mvp}
- **Growth Stage:** ${feasibility.cloudArchitecture.estimatedMonthlyCloudCost.growth}
- **Scale Stage:** ${feasibility.cloudArchitecture.estimatedMonthlyCloudCost.scale}

### Third-Party APIs Integrated
${feasibility.cloudArchitecture.thirdPartyAPIs
  .map((api) => `- **${api.name}**: ${api.purpose} (*${api.costTier}*)`)
  .join("\n")}

---

## 7. AI Scoring Engine Breakdown
${feasibility.scoringEngine ? `
- **Startup Viability Score:** ${feasibility.scoringEngine.viabilityScore} / 100
- **Verdict:** **${feasibility.scoringEngine.verdict}**
- **Percentile Ranking:** ${feasibility.scoringEngine.percentileRank}

| Evaluation Dimension | Score | Weight | Impact | Rationale |
|---|---|---|---|---|
${feasibility.scoringEngine.factors
  .map(
    (f) =>
      `| **${f.name}** | ${f.score}% | ${f.weight}% | ${f.impact} | ${f.rationale} |`
  )
  .join("\n")}
` : `Viability Score: ${feasibility.overallScore}/100`}

---

## 8. MVP (Minimum Viable Product) Recommendation & 4-Week Sprint Plan
${feasibility.mvpRecommendation ? `
- **MVP Scope:** ${feasibility.mvpRecommendation.mvpName} (${feasibility.mvpRecommendation.timelineWeeks} Weeks to Launch)
- **Core Value Proposition:** ${feasibility.mvpRecommendation.coreValueProposition}

### Must-Have Core Features (P0)
${feasibility.mvpRecommendation.featureBacklog.mustHave.map((f) => `- [x] ${f}`).join("\n")}

### 4-Week Rapid Sprint Plan
${feasibility.mvpRecommendation.fourWeekSprintPlan
  .map(
    (s) =>
      `#### Week ${s.week}: ${s.title}\n- **Deliverable:** ${s.deliverable}\n${s.goals
        .map((g) => `  - ${g}`)
        .join("\n")}`
  )
  .join("\n\n")}
` : ""}

---

## 9. 12-Month Business Roadmap
${feasibility.businessRoadmap ? `
${feasibility.businessRoadmap.phases
  .map(
    (p) =>
      `### Phase ${p.phase}: ${p.title} (${p.timeframe}) — Status: ${p.status}\n- **Funding Target:** ${p.fundingGoal}\n- **Success KPIs (Key Performance Indicators):** ${p.keyMetrics}\n- **Milestones:**\n${p.milestones
        .map((m) => `  - [ ] ${m}`)
        .join("\n")}`
  )
  .join("\n\n")}
` : ""}

---

## 10. Risk Analysis & Mitigation Matrix
| Risk Vector | Probability | Severity | Mitigation Strategy |
|---|---|---|---|
${feasibility.risksAndMitigations
  .map(
    (r) =>
      `| **${r.risk}** | ${r.probability} | ${r.severity} | ${r.mitigation} |`
  )
  .join("\n")}

---

## 11. Immediate Founder Next Steps
${feasibility.goNextSteps.map((step, idx) => `${idx + 1}. ${step}`).join("\n")}
`;
}
